grafana:
  admin:
    existingSecret: grafana-admin-credentials
    userKey: admin-user
    passwordKey: admin-password

  service:
    type: ClusterIP

  persistence:
    enabled: false

  defaultDashboardsEnabled: true

  grafana.ini:
    server:
      domain: grafana.andresantos.click
      root_url: https://grafana.andresantos.click/

alertmanager:
  enabled: true

prometheus:
  prometheusSpec:
    retention: 7d
    storageSpec: null

kube-state-metrics:
  enabled: true

nodeExporter:
  enabled: true